### ISSUE TITLE
Rosidl empy 4.0 is incompatible

### ISSUE THREAD

**Issue by kasperg3** [edouardrolland/vscode_ros2_px4_workspace#3]
https://github.com/ros2/rosidl/issues/779

The container will not build due to an error in empy which ros2 uses. 

Either wait for a fix in ros2 or use a static version of empy in the dockerfile. 
Potential fix: 
pip install empy==3.3.4 . . .

**Comment by kasperg3** [comment]
Fixed in the latest release

**Comment by UltraHertzz** [comment]
it seems that in empy==4.0.x still have the question, reinstall empy==3.3.4 will fix the problem

**Comment by kasperg3** [comment]
We have build a new docker image which the devcontainer now uses. It has been fixed here: https://github.com/edouardrolland/vscode_ros2_px4_workspace/blob/4522f5ea97d447c3926a3c5f185782c9f8f4e7c1/px4/humble.Dockerfile#L17

Let me know if you run into any problems using the dev container.
